### ISSUE TITLE
decodedLen() assumes max of int64, but format limits block size to uint32

### ISSUE THREAD

**Issue by dgryski** [golang/snappy#15]
In `decodedLen()`,

```go
	if uint64(int(v)) != v {
		return 0, 0, errors.New("snappy: decoded block is too large")
	}
```

However, the snappy format description (and the C and C++ implementations) limit this varint to 32-bits:

https://github.com/google/snappy/blob/master/format_description.txt

>The stream starts with the uncompressed length (up to a maximum of 2^32 - 1),
> stored as a little-endian varint.

This check should instead use
```go
	if uint64(uint32(v)) != v {
		return 0, 0, errors.New("snappy: decoded block is too large")
	}
```

I can file a PR here or a CL if this project is using gerrit if you'd like.

This bug dates from the Go 1.1 integer size change.

**Comment by cespare** [comment]
@dgryski you should file a PR.
