### ISSUE TITLE
support API for official snappy framing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [golang/snappy#2]
```
I would like to see some functions to facilitate building a framed snappy 
stream. Some functions that would be helpful:

EncodeFrame(dst, src []byte)
StartFrames(dst)
FinishFrames(dst)

Please provide any additional information below.

The official snappy repository has a document describing the framing format for 
snappy (http://code.google.com/p/snappy/source/browse/trunk/framing_format.txt) 
 
```

Original issue reported on code.google.com by `jehiah` on 19 Jul 2012 at 3:58

**Comment by nigeltao** [comment]
There are io.Reader and io.Writer implementations for the official framing (streaming) format: https://github.com/google/snappy/blob/master/framing_format.txt

These have existed since February 2015 (https://codereview.appspot.com/199400043/) but I did not update this bug at the time.
