### ISSUE TITLE
framing format implementation

### ISSUE THREAD

**Issue by glycerine** [golang/snappy#24]
It is great that this snappy golang library is getting some love, especially assembly language love. Nice!

A while back I wrote a Go implementation of the framing/streaming spec for snappy. It is here:
https://github.com/glycerine/go-unsnap-stream

If the maintainers of golang/snappy would like to adopt my implementation and integrate the framing implementation with golang/snappy library or a future Go standard lib for snappy, you have my blessing. (Especially if you want to re-write parts in assembly to make it even faster.)

Thanks again for improving golang/snappy.

**Comment by nigeltao** [comment]
Ah, my own implementation of the framing format was finally submitted about a year ago (https://codereview.appspot.com/199400043/).

It is already in golang/snappy. Look for Reader and Writer.
