### ISSUE TITLE
Fuzz new decoder implementation?

### ISSUE THREAD

**Issue by dgryski** [golang/snappy#25]
The existing Go decoded was no doubt tested with go-fuzz.  Does the new asm decoder also need heavy testing with bad inputs?

**Comment by nigeltao** [comment]
Probably. Honeset question: are you volunteering?

**Comment by dgryski** [comment]
I can find some time to do this.  I will also use the fuzz function to ensure identical output between the pure-Go decoder and the assembly version.

**Comment by dgryski** [comment]
I've now run several billion fuzz attmempts through https://gist.github.com/dgryski/6f1b8caebf65dc489f7b with no crashes.  Note this requires renaming the decoder routines slightly so that both the Go and the assembly decoder are available.

This can probably be closed.
