### ISSUE TITLE
SemVer Releases

### ISSUE THREAD

**Issue by prateek** [golang/snappy#41]
Any chance you'd be willing to tag releases following semver?

**Comment by creachadair** [comment]
I think this was mostly addressed by the follow-on to https://github.com/golang/snappy/pull/46.

**Comment by maruel** [comment]
@nigeltao you may want to `git tag v0.0.2` because v0.0.1 is quite old now.

**Comment by nigeltao** [comment]
`v0.0.2` tagged.
